name: ddns
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:
  args: ^2.4.0
  io: ^1.0.4
  json_annotation: ^4.8.1
  logging: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  stack_trace: ^1.11.1

dev_dependencies:
  build_runner: ^2.4.7
  http: ^1.1.0
  json_serializable: ^6.7.1
  lints: ^2.1.0
  shelf_router_generator: ^1.1.0
  test: ^1.24.0
